### ISSUE TITLE
Is it possible to run YOLOPv2 with camera in real-time

### ISSUE THREAD

**Issue by emredaglier** [CAIC-AD/YOLOPv2#43]
Currently project does not contain live camera ability.

YOLOP
```
# Set Dataloader
if opt.source.isnumeric():
        cudnn.benchmark = True  # set True to speed up constant image size inference
        dataset = LoadStreams(opt.source, img_size=opt.img_size)
        bs = len(dataset)  # batch_size
    else:
        dataset = LoadImages(opt.source, img_size=opt.img_size)
        bs = 1  # batch_size
```

YOLOPv2
```
 # Set Dataloader
    vid_path, vid_writer = None, None
    dataset = LoadImages(source, img_size=imgsz, stride=stride)
```

Is it possible to make tweak to have a live cam feed?

**Comment by PlutoXN** [comment]
Hello, have you implemented real-time detection with the camera now?

**Comment by Azpril45** [comment]
> Currently project does not contain live camera ability.
> 
> YOLOP
> 
> ```
> # Set Dataloader
> if opt.source.isnumeric():
>         cudnn.benchmark = True  # set True to speed up constant image size inference
>         dataset = LoadStreams(opt.source, img_size=opt.img_size)
>         bs = len(dataset)  # batch_size
>     else:
>         dataset = LoadImages(opt.source, img_size=opt.img_size)
>         bs = 1  # batch_size
> ```
> 
> YOLOPv2
> 
> ```
>  # Set Dataloader
>     vid_path, vid_writer = None, None
>     dataset = LoadImages(source, img_size=imgsz, stride=stride)
> ```
> 
> Is it possible to make tweak to have a live cam feed?


Hi @emredaglier emredaglie, have you implemented real-time detection with the camera now?

**Comment by Azpril45** [comment]
> Hello, have you implemented real-time detection with the camera now?

Hi @PlutoXN , have you got any progress now with webcam?

**Comment by neurodisk23** [comment]
@emredaglier @PlutoXN @Azpril45  Have you tried changing the source in line 20 of demo.py
`  parser.add_argument('--source', type=str, default='data/example.jpg', help='source')  # file/folder, 0 for webcam`

you can pass your webcam serial number as an input.

Let me know if the problem persist.

**Comment by zenchf** [comment]
@neurodisk23 i had this:

(yolopv2) legaca@legaca:~/Desktop/adas/YOLOPv2$ python custom_demo.py --source 0
Namespace(weights='data/weights/yolopv2.pt', source='0', img_size=640, conf_thres=0.3, iou_thres=0.45, device='0', save_conf=False, save_txt=False, nosave=False, classes=None, agnostic_nms=False, project='runs/detect', name='exp', exist_ok=False)
Traceback (most recent call last):
  File "/home/legaca/Desktop/adas/YOLOPv2/custom_demo.py", line 180, in <module>
    detect()
  File "/home/legaca/Desktop/adas/YOLOPv2/custom_demo.py", line 61, in detect
    dataset = LoadImages(source, img_size=imgsz, stride=stride)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/legaca/Desktop/adas/YOLOPv2/utils/utils.py", line 401, in __init__
    raise Exception(f'ERROR: {p} does not exist')
Exception: ERROR: /home/legaca/Desktop/adas/YOLOPv2/0 does not exist
